runtime: nodejs
env: flex

env_variables:
  CORS_ORIGIN: https://allmywallets.io
  VAPID_PUBLIC: BMb_DJI8t5r2ModG7eXXHPQJCC6xn-gtZolzrybjO8tDIKprH2X4T-9Kg_5HGNwxcPZNZ_C6LjJlow7X83l4YVo
  VAPID_PRIVATE: zbrOK1golpayrGbxmEAqBNQj7rsbJ58n_u9tEKyYe68

# Todo: should be removed on public release
manual_scaling:
  instances: 1
resources:
  cpu: 1
  memory_gb: 0.5
  disk_size_gb: 10
